/**
 * PRV Projects — index pentru căutare internă (static)
 */
window.PRV_SEARCH_INDEX = [
  { url: "index.html", type: "page", tags: "acasă home renovări" },
  { url: "servicii.html", type: "page", i18n: "nav.services", tags: "servicii renovări bucătărie baie design" },
  { url: "proiecte.html", type: "page", i18n: "nav.work", tags: "proiecte portfolio lucrări" },
  { url: "de-ce-noi.html", type: "page", i18n: "nav.why", tags: "de ce noi avantaje garanție" },
  { url: "despre-noi.html", type: "page", i18n: "nav.about", tags: "despre echipă istorie" },
  { url: "contact.html", type: "page", i18n: "nav.contact", tags: "contact ofertă email" },
  { url: "faq.html", type: "page", i18n: "faq.title", tags: "faq întrebări cost garanție termen" },
  {
    url: "confidentialitate.html",
    type: "page",
    i18n: "privacy.title",
    tags: "confidențialitate gdpr cookies privacy politică date",
  },
  {
    url: "projects/aurora-residence.html",
    type: "project",
    title: "Aurora Residence",
    i18n: "work.p1",
    tags: "apartament bruxelles renovare completă",
  },
  {
    url: "projects/nova-loft.html",
    type: "project",
    title: "Nova Loft",
    i18n: "work.p2",
    tags: "loft antwerpen open space",
  },
  {
    url: "projects/orbit-heritage.html",
    type: "project",
    title: "Orbit Heritage",
    i18n: "work.p3",
    tags: "heritage bruxelles clădire veche",
  },
  {
    url: "projects/lumen-dental.html",
    type: "project",
    title: "Lumen Dental",
    i18n: "work.p4",
    tags: "cabinet medical dental clinica",
  },
  {
    url: "projects/velvet-court.html",
    type: "project",
    title: "Velvet Court",
    i18n: "work.p5",
    tags: "apartament finisaje premium",
  },
  {
    url: "projects/canal-house-gent.html",
    type: "project",
    title: "Canal House Gent",
    i18n: "work.p6",
    tags: "gent canal casă",
  },
  {
    url: "projects/atlas-kitchen.html",
    type: "project",
    title: "Atlas Kitchen",
    i18n: "work.p7",
    tags: "bucătărie kitchen quartz",
  },
  {
    url: "projects/serene-bath.html",
    type: "project",
    title: "Serene Bath",
    i18n: "work.p8",
    tags: "baie bathroom wellness",
  },
  {
    url: "projects/studio-nine.html",
    type: "project",
    title: "Studio Nine",
    i18n: "work.p9",
    tags: "studio apartament mic",
  },
  {
    url: "projects/harbor-office.html",
    type: "project",
    title: "Harbor Office",
    i18n: "work.p10",
    tags: "birou office comercial",
  },
  {
    url: "blog/index.html",
    type: "blog",
    i18n: "nav.blog",
    tags: "blog articole renovare",
  },
  {
    url: "blog/cost-renovare-2026.html",
    type: "blog",
    title: "Cost renovare 2026",
    tags: "buget cost preț 2026",
  },
  {
    url: "blog/greseli-buget-renovare.html",
    type: "blog",
    title: "Greșeli buget renovare",
    tags: "buget greșeli economii",
  },
  {
    url: "blog/premium-finishes-glass-beton.html",
    type: "blog",
    title: "Finisaje premium",
    tags: "finisaje sticlă beton materiale",
  },
  {
    url: "shop/index.html",
    type: "shop",
    title: "PRV Shop",
    tags: "shop magazin finisaje materiale pachete renovare cumpărături",
  },
];
